export const FETCH_ALL: string = 'FETCH_ALL'
export const CREATE: string = 'CREATE'
export const UPDATE: string = 'UPDATE'
export const DELETE: string = 'DELETE'
export const LIKE: string = 'LIKE'
export const AUTH: string = 'AUTH'
export const LOGOUT: string = 'LOGOUT'
